name: Build and Push catgpt container image to Yandex Container Registry

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 

jobs: 

  build: 
  
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CR_REGISTRY: crp9vpda7crad1c4a2d8
        CR_REPOSITORY: catgpt
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
